baseURL = "/"
languageCode = "en-us"
title = "My New Site"
theme = "hyde"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "spf13"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
[params]
themeColor = "theme-base-09"
description = "With theme"
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/desirajusantosh/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/desirajusantosh/"}
  ]
