	[build]
	publish = "exampleSite/public"
        command = "cd exampleSite && hugo --themesDir ../.."
	
	[context.production.environment]
	HUGO_VERSION = "0.62.2"
	HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
